# -*- coding: utf-8 -*-
# vim: ft=yaml
---
driver:
  name: vagrant

provisioner:
  name: salt_solo
  formula: jenkins
  state_top:
    base:
      "*":
        - jenkins

platforms:
  - name: bento/debian-8

suites:
  - name: default

  - name: custom
    provisioner:
      pillars-from-files:
        jenkins.sls: pillar-custom.sls
      pillars:
        top.sls:
          base:
            "*":
              - jenkins
